version: '3'
services:
  postgres:
    container_name: pg-contato-gh
    restart: always
    image: postgres:latest
    expose:
      - 5432
    environment:
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASS
      - POSTGRES_DB=$PG_DB
    volumes:
      - ../pg-contato-gh/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
